apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: 01-example-kgateway
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 80
