apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: 05-opentelemetry
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
