apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-db-credentials-ssm-parameters
  namespace: example-refresh-secrets-aws
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: ssm-parameterstore
    kind: ClusterSecretStore
  target:
    name: mysql-credentials-ssm-parameters
    creationPolicy: Owner    
    template:
      engineVersion: v2
      data: 
        credentials: |
          db_con="{{ .db_url }}"
          db_user="{{ .db_username }}"
          db_password="{{ .db_password }}"
        
  data:
  - secretKey: db_url
    remoteRef:
      key: /kubecon26/examples/03-refresh-secrets-aws/url
  - secretKey: db_username
    remoteRef:
      key: /kubecon26/examples/03-refresh-secrets-aws/userid
  - secretKey: db_password
    remoteRef:
      key: /kubecon26/examples/03-refresh-secrets-aws/password

