apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: ssm-parameterstore
spec:
  provider:
    aws:
      service: ParameterStore
      region: ##AWS-Region##
      auth:
        secretRef:
          accessKeyIDSecretRef:
            namespace: 03-example-refresh-secrets-aws
            name: ssm-parameters
            key: access_key
          secretAccessKeySecretRef:
            namespace: 03-example-refresh-secrets-aws
            name: ssm-parameters
            key: secret_access_key
            