# You would normally use a cluster issuer here, see: https://cert-manager.io/docs/configuration/selfsigned/

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: kgateway-system
spec:
  ca:
    secretName: root-secret