apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: tls-route-terminate
  namespace: 01-kgateway-tlsroute-terminate
spec:
  hostnames:
    - "www.example.com"
    - "example.com"
  parentRefs:
    - name: tlsroute-terminate-gateway
      namespace: kgateway-system
      sectionName: tls-terminate
  rules:
    - backendRefs:
        - name: nginx-service
          port: 1234